use fms;
# 插入文件模板数据
INSERT INTO fms_model_bean (model_code, partner_group_name, partner_group_code, partner_group_type, partner_code, partner_name, mail_receiver_address, mail_cc_address, short_msg_receiver, wechat_receiver, model_file_code, model_file_name, model_name, file_suffix, need_out_send, loan_contract_flag, relate_to_mortgage_type, service_function_no) VALUES ('d_mr_0084', '测试资方', 'A00031', 'management', NULL, '测试1', NULL, NULL, NULL, NULL, '6155be11-843e-11e7-8b43-1866dae83f00', '同意锁网签确认书（供渠道签）.ftl', '同意锁网签确认书（供渠道签）', 'doc', 'N', 'N', 'Y', 'G001');
INSERT INTO fms_model_bean (model_code, partner_group_name, partner_group_code, partner_group_type, partner_code, partner_name, mail_receiver_address, mail_cc_address, short_msg_receiver, wechat_receiver, model_file_code, model_file_name, model_name, file_suffix, need_out_send, loan_contract_flag, relate_to_mortgage_type, service_function_no) VALUES ('d_mr_0085', '测试资方', 'A00031', 'management', NULL, '测试2', NULL, NULL, NULL, NULL, '6be01d5a-8437-11e7-8b43-1866dae83f00', '配合卖房承诺书.ftl', '配合卖房承诺书', 'doc', 'N', 'N', 'N', 'G001');
INSERT INTO fms_model_bean (model_code, partner_group_name, partner_group_code, partner_group_type, partner_code, partner_name, mail_receiver_address, mail_cc_address, short_msg_receiver, wechat_receiver, model_file_code, model_file_name, model_name, file_suffix, need_out_send, loan_contract_flag, relate_to_mortgage_type, service_function_no) VALUES ('d_mr_0086', '测试担保', 'C00032', 'guarantee_corporation', NULL, NULL, NULL, NULL, NULL, NULL, '90ecabdd-8435-11e7-8b43-1866dae83f00', '多套房产共同还款承诺书.ftl', '多套房产共同还款承诺书', 'doc', 'N', 'N', 'N', 'G001');
INSERT INTO fms_model_bean (model_code, partner_group_name, partner_group_code, partner_group_type, partner_code, partner_name, mail_receiver_address, mail_cc_address, short_msg_receiver, wechat_receiver, model_file_code, model_file_name, model_name, file_suffix, need_out_send, loan_contract_flag, relate_to_mortgage_type, service_function_no) VALUES ('d_mr_0087', '测试保险', 'B00033', 'insurance_company', NULL, NULL, NULL, NULL, NULL, NULL, '66a87eeb-8409-11e7-8b43-1866dae83f00', '承租人放弃优先购买权承诺书.ftl', '承租人放弃优先购买权承诺书', 'doc', 'N', 'N', 'Y', 'G001');
INSERT INTO fms_model_bean (model_code, partner_group_name, partner_group_code, partner_group_type, partner_code, partner_name, mail_receiver_address, mail_cc_address, short_msg_receiver, wechat_receiver, model_file_code, model_file_name, model_name, file_suffix, need_out_send, loan_contract_flag, relate_to_mortgage_type, service_function_no) VALUES ('d_mr_0088', '海尔金融有限公司', 'A00034', 'management', NULL, '海尔金融', NULL, NULL, NULL, NULL, '68b3498d-8404-11e7-8b43-1866dae83f00', '债权转让协议.ftl', '债权转让协议', 'doc', 'N', 'N', 'Y', 'G001');
INSERT INTO fms_model_bean (model_code, partner_group_name, partner_group_code, partner_group_type, partner_code, partner_name, mail_receiver_address, mail_cc_address, short_msg_receiver, wechat_receiver, model_file_code, model_file_name, model_name, file_suffix, need_out_send, loan_contract_flag, relate_to_mortgage_type, service_function_no) VALUES ('d_mr_0091', '海尔金融有限公司', 'A00034', 'management', NULL, '张瑞明', NULL, NULL, NULL, NULL, '6c4c8784-8401-11e7-8b43-1866dae83f00', '借款合同.ftl', '借款合同', 'doc', 'N', 'Y', 'Y', 'G001');
INSERT INTO fms_model_bean (model_code, partner_group_name, partner_group_code, partner_group_type, partner_code, partner_name, mail_receiver_address, mail_cc_address, short_msg_receiver, wechat_receiver, model_file_code, model_file_name, model_name, file_suffix, need_out_send, loan_contract_flag, relate_to_mortgage_type, service_function_no) VALUES ('d_mr_0090', '上海担保有限公司', 'C00035', 'guarantee_corporation', '', NULL, 'app@123.com;ccc@123.com', 'app1@123.com;ccc1@123.com', '13302125263;18856239568', '18852146325', 'b380c4d5-836f-11e7-8b43-1866dae83f00', '保证合同.ftl', '保证合同', 'doc', 'N', 'N', 'Y', 'G001');
INSERT INTO fms_model_bean (model_code, partner_group_name, partner_group_code, partner_group_type, partner_code, partner_name, mail_receiver_address, mail_cc_address, short_msg_receiver, wechat_receiver, model_file_code, model_file_name, model_name, file_suffix, need_out_send, loan_contract_flag, relate_to_mortgage_type, service_function_no) VALUES ('d_mr_0089', '太平洋保险有限公司', 'B00036', 'insurance_company', NULL, NULL, 'mail', 'cc', 'shortmessage', 'wechat', '744e468f-8360-11e7-8b43-1866dae83f00', '反担保合同.ftl', '反担保合同', 'doc', 'N', 'N', 'Y', 'G001');

INSERT INTO fms_model_bean (model_code, partner_group_name, partner_group_code, partner_group_type, partner_code, partner_name, mail_receiver_address, mail_cc_address, short_msg_receiver, wechat_receiver, model_file_code, model_file_name, model_name, file_suffix, need_out_send, loan_contract_flag, relate_to_mortgage_type, service_function_no) VALUES ('d_mr_0092', '海尔金融有限公司', 'A00034', 'management', NULL, '海尔金融', NULL, NULL, NULL, NULL, '6c4c8784-8401-11e7-8b43-1866dae83f00', '借款合同.ftl', '借款合同', 'doc', 'N', 'Y', 'Y', 'G001');